In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2
print(result)

[ 1  4  9 16 25]


In [6]:
result = arr + 10 #Broadcasting 10 is added to each element

In [7]:
result 

array([11, 12, 13, 14, 15])

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = (arr1 + arr2)
print(result)

[[2 4 6]
 [5 7 9]]
