In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])


In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.astype("float64")

array([1., 2., 3., 4., 5.])

In [8]:
arr.dtype

dtype('int64')

In [9]:
arrr = np.array([1 + 2j, 3 + 4j, 5 + 6j])

In [10]:
arrr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [11]:
arrr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype = 'complex128')

In [12]:
arrr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [13]:
arrr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype = 'complex128')
print(arrr)

[1.+2.j 3.+4.j 5.+6.j]
