In [1]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
flat = arr.flatten()


In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[0]

1

In [11]:
flat[9]

10

In [12]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
flat[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
flat[:12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
b = flat[2 : 7]

In [17]:
b

array([3, 4, 5, 6, 7])

In [18]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
b[2] = 11

In [20]:
b

array([ 3,  4, 11,  6,  7])

In [21]:
flat

array([ 1,  2,  3,  4, 11,  6,  7,  8,  9, 10, 11, 12])