In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [5]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])